# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fsnctlst < Formula
  desc "fusioncatalyst CLI is a tool for managing data contracts and AI prompts."
  homepage ""
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/fusioncatalyst/cli/releases/download/0.0.1/cli_Darwin_x86_64.tar.gz"
      sha256 "aba29f3497f690a3eaf772ef509344e37a04fe9bdfdb179f5435a2cb489ea751"

      def install
        bin.install "fsnctlst"
      end
    end
    on_arm do
      url "https://github.com/fusioncatalyst/cli/releases/download/0.0.1/cli_Darwin_arm64.tar.gz"
      sha256 "bf22faf11921745ded64ecd7c52af46a12e193a83dd486eba782ddb6b623650d"

      def install
        bin.install "fsnctlst"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fusioncatalyst/cli/releases/download/0.0.1/cli_Linux_x86_64.tar.gz"
        sha256 "d9356596b9d7502c9e2c06dc7b7995f12ae4035af0618c6c124e9dd6fdd36835"

        def install
          bin.install "fsnctlst"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fusioncatalyst/cli/releases/download/0.0.1/cli_Linux_arm64.tar.gz"
        sha256 "e016dd618e937326ff8d8e27595bb07d6c2bf4ac53d678d02395e444dd63fb73"

        def install
          bin.install "fsnctlst"
        end
      end
    end
  end

  test do
    system "#{bin}/fsnctlst --version"
  end
end
