# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Paw < Formula
  desc "paw CLI is an official fusioncat tool for managing data contracts and AI prompts."
  homepage ""
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/fusioncatltd/paw/releases/download/0.0.1/paw_Darwin_x86_64.tar.gz"
      sha256 "0dd41d6ad081810bc15ac3fdc889983d599c159d0eb601d6c21cefd6783a2214"

      def install
        bin.install "paw"
      end
    end
    on_arm do
      url "https://github.com/fusioncatltd/paw/releases/download/0.0.1/paw_Darwin_arm64.tar.gz"
      sha256 "b69603ac4beab277feebe47454c7335507194989de92ed0b1fcf3afc89ce92b1"

      def install
        bin.install "paw"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fusioncatltd/paw/releases/download/0.0.1/paw_Linux_x86_64.tar.gz"
        sha256 "eeca2974593826d5fae8d66297e350532aa01ba123f6c92fb8b2726d46883761"

        def install
          bin.install "paw"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fusioncatltd/paw/releases/download/0.0.1/paw_Linux_arm64.tar.gz"
        sha256 "07d86b199a5d4837a2bb5655c9cecbbe0a37d62a6646fd04adafb20a28cba0f9"

        def install
          bin.install "paw"
        end
      end
    end
  end

  test do
    system "#{bin}/paw --version"
  end
end
