# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Paw < Formula
  desc "paw CLI is an official fusioncat tool for managing data contracts and AI prompts."
  homepage ""
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fusioncatltd/paw/releases/download/0.0.2/paw_Darwin_x86_64.tar.gz"
      sha256 "1d3252837de81317e494090f9ee227c0a37316eb8966bf8379f9a8f0c16ffe46"

      def install
        bin.install "paw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fusioncatltd/paw/releases/download/0.0.2/paw_Darwin_arm64.tar.gz"
      sha256 "debfc327fefed7acbfef1b8230eb3de069fe004837073f513179bf170261c150"

      def install
        bin.install "paw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/fusioncatltd/paw/releases/download/0.0.2/paw_Linux_x86_64.tar.gz"
      sha256 "e008ff771a9e375e8bf5f295be6693ba2a37bb845a04d3c1a4c3eed19df91586"
      def install
        bin.install "paw"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/fusioncatltd/paw/releases/download/0.0.2/paw_Linux_arm64.tar.gz"
      sha256 "84f88ca4ef90c8bf1fe2043fadb1f8124be851034fce4c1c796197b2bbe2a634"
      def install
        bin.install "paw"
      end
    end
  end

  test do
    system "#{bin}/paw --version"
  end
end
